version: "2"
services:
  server:
    container_name: server_container
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    depends_on:
      - database
  client:
    container_name: client_container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  database:
    container_name: database_container
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
